// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VsfUIClient is the client API for VsfUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VsfUIClient interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VsfUI_ListFunctionSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type vsfUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVsfUIClient(cc grpc.ClientConnInterface) VsfUIClient {
	return &vsfUIClient{cc}
}

func (c *vsfUIClient) ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VsfUI_ListFunctionSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VsfUI_ServiceDesc.Streams[0], "/v1.VsfUI/ListFunctionSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vsfUIListFunctionSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VsfUI_ListFunctionSpecsClient interface {
	Recv() (*ListFunctionSpecsResponse, error)
	grpc.ClientStream
}

type vsfUIListFunctionSpecsClient struct {
	grpc.ClientStream
}

func (x *vsfUIListFunctionSpecsClient) Recv() (*ListFunctionSpecsResponse, error) {
	m := new(ListFunctionSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vsfUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VsfUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VsfUIServer is the server API for VsfUI service.
// All implementations must embed UnimplementedVsfUIServer
// for forward compatibility
type VsfUIServer interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(*ListFunctionSpecsRequest, VsfUI_ListFunctionSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVsfUIServer()
}

// UnimplementedVsfUIServer must be embedded to have forward compatible implementations.
type UnimplementedVsfUIServer struct {
}

func (UnimplementedVsfUIServer) ListFunctionSpecs(*ListFunctionSpecsRequest, VsfUI_ListFunctionSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFunctionSpecs not implemented")
}
func (UnimplementedVsfUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVsfUIServer) mustEmbedUnimplementedVsfUIServer() {}

// UnsafeVsfUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VsfUIServer will
// result in compilation errors.
type UnsafeVsfUIServer interface {
	mustEmbedUnimplementedVsfUIServer()
}

func RegisterVsfUIServer(s grpc.ServiceRegistrar, srv VsfUIServer) {
	s.RegisterService(&VsfUI_ServiceDesc, srv)
}

func _VsfUI_ListFunctionSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFunctionSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VsfUIServer).ListFunctionSpecs(m, &vsfUIListFunctionSpecsServer{stream})
}

type VsfUI_ListFunctionSpecsServer interface {
	Send(*ListFunctionSpecsResponse) error
	grpc.ServerStream
}

type vsfUIListFunctionSpecsServer struct {
	grpc.ServerStream
}

func (x *vsfUIListFunctionSpecsServer) Send(m *ListFunctionSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VsfUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VsfUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VsfUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VsfUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VsfUI_ServiceDesc is the grpc.ServiceDesc for VsfUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VsfUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VsfUI",
	HandlerType: (*VsfUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VsfUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFunctionSpecs",
			Handler:       _VsfUI_ListFunctionSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vsf-ui.proto",
}
